import {
  AccountableTradePlanSchema,
  type AccountableTradePlan,
  type MarketScan,
  type RiskMode,
  type TradeIdea,
} from "@kr8tiv/shared-schemas";

export type BuildTradePlanOptions = {
  marginQuote?: number;
  riskMode?: RiskMode;
};

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function rounded(value: number): number {
  return Math.round(value);
}

export function chooseRiskMode(idea: TradeIdea): RiskMode {
  if (idea.horizon === "swing") return "core";
  return idea.confidence >= 0.8 ? "sniper" : "medium";
}

export function suggestLeverage(idea: TradeIdea, riskMode: RiskMode): number {
  const normalizedConfidence = clamp((idea.confidence - 0.4) / 0.55, 0, 1);
  if (riskMode === "sniper") {
    return rounded(30 + normalizedConfidence * 70);
  }
  if (riskMode === "medium") {
    return rounded(10 + normalizedConfidence * 40);
  }
  return rounded(10 + normalizedConfidence * 20);
}

function defaultMarginQuote(riskMode: RiskMode): number {
  if (riskMode === "medium") return 25;
  return riskMode === "sniper" ? 10 : 50;
}

function makeSignalId(idea: TradeIdea): string {
  const entry = Math.round(idea.entryPrice * 100);
  return `signal:${idea.symbol}:${idea.direction}:${idea.horizon}:${entry}`;
}

export function buildTradePlanFromIdea(
  idea: TradeIdea,
  options: BuildTradePlanOptions = {},
): AccountableTradePlan {
  const riskMode = options.riskMode ?? chooseRiskMode(idea);
  const target = idea.targets[0] ?? idea.entryPrice;

  return AccountableTradePlanSchema.parse({
    symbol: idea.symbol,
    market: "mexc-futures",
    direction: idea.direction,
    horizon: idea.horizon,
    riskMode,
    leverage: suggestLeverage(idea, riskMode),
    marginQuote: options.marginQuote ?? defaultMarginQuote(riskMode),
    entryPrice: idea.entryPrice,
    stopLossPrice: idea.invalidationPrice,
    takeProfitPrice: target,
    thesis: idea.thesis,
    journalNote:
      "Generated by deterministic futures model; Matt must confirm before execution.",
    generatedFromSignalId: makeSignalId(idea),
    createdAtMs: Date.now(),
  });
}

export function buildTradePlansFromScan(
  scan: MarketScan,
  options: BuildTradePlanOptions = {},
): AccountableTradePlan[] {
  return scan.ideas.map((idea) => buildTradePlanFromIdea(idea, options));
}
